Show board in Webapp
marmelab/kamon pull request #24
Opened 2023-04-24 14:58 UTC by adguernier

[Trello Card](https://trello.com/c/ghjVGpXv/20-1-as-hayao-i-want-to-see-a-real-hexagon-board-game)

[Capture vidéo du 25-04-2023 12:06:26.webm](https://user-images.githubusercontent.com/7949510/234244836-f1a1d38f-4a28-4e2c-b8e7-558a04b83acc.webm)

2023-04-24 15:47 UTC, fzaninotto commented
I don't know what this is about

2023-04-25 10:08 UTC, paulSanchezMarmelab commented on webapp/src/app.controller.spec.ts
> +  describe("root", () => {
This test isn't valid.

2023-04-25 11:20 UTC, paulSanchezMarmelab commented
For later, maybe `makefile.ci.yml` should start both `make test-cli` and `make test-webapp`

2023-04-25 11:38 UTC, fzaninotto requested changes
Great UI! I just think that the played locations deserve a better UI.

2023-04-25 11:38 UTC, fzaninotto commented on webapp/public/app.css
> +  --m: 4px;
Could you choose more explicit variable names?

2023-04-25 11:38 UTC, fzaninotto commented on webapp/public/app.css
> +  top: -20px;
It seems a bit too specific for such a generic element. Shouldn't you style uls of a particular class instead?

2023-04-25 11:38 UTC, fzaninotto commented on webapp/public/app.css
> +  height: calc(var(--s) * 1.1547);
Magic number, please make it a const with an expressive name, and/or link to the computation for it

2023-04-25 11:38 UTC, fzaninotto commented on webapp/public/app.css
> +  margin-bottom: calc(var(--m) - var(--s)*0.2885);
same

2023-04-25 11:38 UTC, fzaninotto commented on webapp/src/app.controller.ts
> +    const game = [
:+1: To work on the UI, you use static data. Great shortcut!

2023-04-25 11:38 UTC, fzaninotto commented on webapp/views/index.hbs
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9
please import static assets, for the sake of learning how to serve them ;)

2023-04-25 13:03 UTC, Nitix approved these changes

2023-04-25 13:32 UTC, merged