Feature ongoing game
marmelab/kamon pull request #6
Opened 2023-04-18 15:38 UTC by paulSanchezMarmelab

[feature_ongoing_game.webm](https://user-images.githubusercontent.com/130989826/232828855-5dc7a588-1957-424a-a31d-56786164c886.webm)

[X] added playedBy support
[X] added lastPlayed support

2023-04-18 20:04 UTC, fzaninotto reviewed
Your code should really separate the game model from the game representation. All your files mix both intents. This will be very hard to maintain.

2023-04-19 07:32 UTC, paulSanchezMarmelab commented
> Your code should really separate the game model from the game representation. All your files mix both intents. This will be very hard to maintain.

I'm not quite sure to see exactly where the issue is. Did you mean that "Tile" should only have render-oriented properties and that logic tied to game states like "playedBy" and "isLastPlayed" should be in a distinct part of the code ?

2023-04-19 09:03 UTC, slax57 commented
I forgot to mention this after I reviewed https://github.com/marmelab/kamon/pull/4, but we should have documented how to run the CLI with the `-f` parameter.

For this time only I don't recommend adding a `makefile` target for this, but instead I would recommend using `yarn` directly.

The command should be something like 

```sh
yarn start -f my_save_file.json
```

Can you add it to the `Readme` on this PR please?

2023-04-19 11:22 UTC, paulSanchezMarmelab commented
> I forgot to mention this after I reviewed #4, but we should have documented how to run the CLI with the `-f` parameter.
> 
> For this time only I don't recommend adding a `makefile` target for this, but instead I would recommend using `yarn` directly.
> 
> The command should be something like
> 
> ```shell
> yarn start -f my_save_file.json
> ```
> 
> Can you add it to the `Readme` on this PR please?

I added instructions to Readme file.

2023-04-19 12:59 UTC, slax57 requested changes

2023-04-19 12:59 UTC, slax57 commented on Readme.md
> +yarn start -f my_save_file.json
```suggestion
## initialize a new game
make run

## resume a game from a target save file
yarn start -f my_save_file.json
```

2023-04-19 12:59 UTC, slax57 commented on src/tile/tile.ts
> +export type Symbols = (typeof symbols)[number];
```suggestion
export type Symbol = (typeof symbols)[number];
```

2023-04-19 12:59 UTC, slax57 commented on src/tile/tile.ts
> +type Players = "black" | "white";
```suggestion
type Player = "black" | "white";
```

2023-04-19 13:04 UTC, slax57 approved these changes

2023-04-19 13:08 UTC, slax57 requested changes

2023-04-19 13:08 UTC, slax57 commented on src/tile/tile.ts
> +  return dynamicChalk(tile.symbol);
```suggestion
  return dynamicChalk(`${tile.symbol} `);
```
Otherwise this is a regression

2023-04-19 13:30 UTC, slax57 approved these changes

2023-04-19 13:30 UTC, merged